name: webmaskitchen
description: A new Flutter project.
version: 1.2.6+16

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animations: ^2.0.2
  dropdown_button2: ^1.5.3
  flutter:
    sdk: flutter
    
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_mailer: ^2.0.1
  flutter_native_splash: ^2.2.1
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.5
  html: ^0.15.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  meta: ^1.8.0
  mobile_scanner: ^2.0.0
  multi_select_flutter: ^4.1.2
  path_provider: ^2.0.10
  shared_preferences: ^2.0.15
  syncfusion_flutter_calendar: ^20.1.56
  syncfusion_flutter_pdf: ^20.1.57-beta
  syncfusion_flutter_signaturepad: ^20.1.56
  syncfusion_localizations: ^20.1.56
  url_launcher: ^6.1.7
  path: ^1.8.0
  data_table_2: ^2.4.2
  universal_html: ^2.0.10
  
  

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"

flutter_icons:
  image_path: 'assets/images/logo_ceginfor.png'
  android: "launcher_icon"
  ios: true

flutter:
  assets:
    - assets/images/logo_ceginfor.png
    - assets/configuracion/
    